### ISSUE TITLE
bl.ock deletion...api changes?

### ISSUE THREAD

**Issue by auremoser** [mbostock/bl.ocks.org#63]
Hello! I just noticed a few days ago that a bl.ocks went down; thereafter my bl.ock count reduced substantially. :( I thought maybe the situation would fix itself but it hasn't and I'm wondering whether perhaps others have not noticed a change, or it there's something wrong with my workflow/gist accounts.

I'm posting here in case others have noted a reduction.

## Context
I have 60 public gists and 28 bl.ocks (currently), what's been conserved in my bl.ocks account appears to be arbitrary (some things from last year, plus things from last week but a bunch absent in between), nothing has changed in my workflow. 

I use bl.ocks for teaching my undergraduates and many of the examples i made are now not live anymore :(, this is no one's problem but my own and I could convert them to gh-pages, but I'm just wondering why it's not working.

<http://bl.ocks.org/auremoser>
<https://gist.github.com/auremoser>

## Tests
I made a new `.md` bl.ock to test this, [just here](https://gist.github.com/auremoser/c42cfe5edff2ff212672), and it doesn't appear among my latests bl.ocks, [here](http://bl.ocks.org/auremoser).

Here are some of the un-rendered gists: 
* <https://gist.github.com/auremoser/4479f13e7bdde9058a30>
* <https://gist.github.com/auremoser/1b5b9cc5c7452c7af1ab>

They are mostly markdown files, so that's why I suspect it's just not supporting markdown anymore :(.

## Possible issues:
* somehow gists that lack an `index.html` or `.js` file don't render even if they are public (I have for example, a bunch of .md files that port to bl.ocks, maybe .md isn't supported in blocks anymore because there is no "rendered" version)
* I use gistup to make my bl.ocks (not sure whether that affects anything).

Sorry to be a bother, I know this is free and I'm totally benefiting from it so it's my problem, but maybe it's affecting other accounts too. And I'd just like to know if there's anything I can do to fix it. Thank you for reading!

**Comment by mbostock** [comment]
In order to appear as a block, **at least one** of the following must be true:

* There must be an `index.html`.
* There must be a Markdown file who name starts with `readme` (case-insensitive) followed by a word boundary; most commonly, `README.md`.

In your case your Markdown files are not named `README.md`. (For example, one is named `blahblah.md`.)

This convention is necessary to provide more explicit control over what is shown as a block. See #62 for example.

I suppose we could relax the constraint and display any block that contains at least one Markdown file (not necessarily named “readme”), but then we’d also need to display that Markdown file as HTML rather than raw code; currently bl.ocks.org only does that for Markdown files named “readme”. But I think it’s better to stick with the current convention as a way for controlling what is shown.

**Comment by auremoser** [comment]
This must have changed recently though, because my blablah.md bl.ocks totes displayed as of last week. I'll update them to readmes, thanks so much for responding!

**Comment by mbostock** [comment]
Yes, I deployed this change recently. Sorry for the confusion.

**Comment by auremoser** [comment]
That's o.k.! Thanks for building it to begin with. Curious that it missed this one though: 
<http://bl.ocks.org/auremoser/72803ba969d0e61ff070>

So strange!

**Comment by mbostock** [comment]
That one appears as a block because it has a [README.md](http://bl.ocks.org/auremoser/raw/72803ba969d0e61ff070/README.md).

The [issue_template.md](http://bl.ocks.org/auremoser/raw/72803ba969d0e61ff070/issue_template.md) is not rendered as HTML because it doesn’t start with the name “readme” followed by a word boundary.

**Comment by auremoser** [comment]
gotcha, thanks!
